### ISSUE TITLE
Need More details of Connection type in RDS and PHP installation in Ubuntu Server 

### ISSUE THREAD

**Issue by VigneshAWS** [iamnvna/php-amazonrds-connect#1]
Connection failed: could not find driver

**Comment by iamnvna** [comment]
Find the code to the type of failure [here.](https://stackoverflow.com/questions/2852748/pdoexception-could-not-find-driver) The code above runs using XAMPP (because of it PHP component) on a localhost.

**Comment by VigneshAWS** [comment]
Hello,
I Started an Ubuntu Server in AWS EC2,
Installed Nginx Webserver and Installed PHP-FPM, I can see the phpInfo() Page successfully in the IP address of the Instance.
I created MySQL DB in RDS and Connected using the Official docs. I am searching for Solutions since 2 days but No luck. Today saw your code in GitHub and tried it and Got result with error message. If you have time, Can you guide me? It will me highly helpful.

**Comment by iamnvna** [comment]
> Hello, I Started an Ubuntu Server in AWS EC2, Installed Nginx Webserver and Installed PHP-FPM, I can see the phpInfo() Page successfully in the IP address of the Instance. I created MySQL DB in RDS and Connected using the Official docs. I am searching for Solutions since 2 days but No luck. Today saw your code in GitHub and tried it and Got result with error message. If you have time, Can you guide me? It will me highly helpful.

Hey, I meant to reply this but it escaped me completely. Have been a bit busy. Have you been able to figure it out?
